[build]
  publish = "."
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin/login"
  to = "/admin/login.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/handler/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
